name: ds_ver2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  dio: ^5.5.0
  go_router: ^14.2.0
  my_app: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter

include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: true
    avoid_print: true
